# SMGAN
#### general settings
name: SMGAN-01
# ddd use_tb_logger: false
scale: 16
Ref_color: RGB # choose gray, y, RGB
gpu_ids: [0,1]

#### datasets
datasets:
  train:
    name: RS-SR19
    data_type: lmdb
    mode: SMGAN
    dataroot_GT: /gpfs/home/huowei/SMG/dataset/train/train_lmdb/HR.lmdb
    dataroot_LQ: /gpfs/home/huowei/SMG/dataset/train/train_lmdb/LR.lmdb

    use_shuffle: true
    n_workers: 2  # per GPU
    batch_size: 4
    GT_size: 480
    use_flip: true
    use_rot: true
  val:
    name: RS-SR19_val_1st
    data_type: lmdb
    mode: SMGAN
    GT_size: 480
    dataroot_GT: /gpfs/home/huowei/SMG/dataset/val/val_1st_lmdb/HR.lmdb
    dataroot_LQ: /gpfs/home/huowei/SMG/dataset/val/val_1st_lmdb/LR.lmdb

#### network structures
network_G:
  nf: 64
  n_blocks: 16
network_D:
  in_nc: 3
  nf: 64

#### path
path:
  strict_load: false
  resume_state: ~
  root: ./exp

train:
  lr_G: !!float 1e-4
  weight_decay_G: 0
  weight_decay_G_grad: 0
  beta1_G: 0.9
  beta2_G: 0.99
  beta1_G_grad: 0.9
  lr_D: !!float 1e-4
  weight_decay_D: 0
  beta1_D: 0.9
  beta2_D: 0.99
  lr_scheme: MultiStepLR

  niter: 120000
  warmup_iter: -1  # no warm up
  lr_steps: [20000, 40000, 60000, 80000]
  lr_gamma: 0.5

  pixel_criterion: l1
  feature_criterion: l1
  gan_type: gan  # gan | ragan
  gradient_pixel_weight: !!float 0  
  l1_init: 20000

  # init 
  # feature_weight: !!float 1e-1  # ααααααααα
  # gan_weight: !!float 1e-3 # ββββββββββ
  # pixel_weight: 1.0 # γγγγγγγγγγγ
  # gradient_gan_weight: !!float 1e-3 # δδδδδδδδδ

  #  α/β/γ/δ = 0.01/0.001/1/0.001   
  # pixel_weight: 1.0                 # γγγγγγγγγγγ → γ = 1
  # feature_weight: !!float 1e-2     # ααααααααα → α = 0.01
  # gan_weight: !!float 1e-3         # ββββββββββ → β = 0.001
  # gradient_gan_weight: !!float 1e-3 # δδδδδδδδδ → δ = 0.001

  #  α/β/γ/δ = 1/0.005/1/0.005
  # pixel_weight: 1.0                 # γγγγγγγγγγγ → γ = 1
  # feature_weight: 1.0              # ααααααααα → α = 1
  # gan_weight: !!float 5e-3         # ββββββββββ → β = 0.005
  # gradient_gan_weight: !!float 5e-3 # δδδδδδδδδ → δ = 0.005
  ##################################################################################
  pixel_weight: 1.0              # γ
  feature_weight: !!float 1e-2   # α
  gan_weight: !!float 1e-3       # β
  gradient_gan_weight: !!float 0  # δ = 0
  # pix_grad_weight: 0.0           # γ(grad) = 0


  # grec
  # pixel_weight: 1.0              # γ
  # feature_weight: !!float 1e-2   # α
  # gan_weight: !!float 1e-3       # β
  # gradient_gan_weight: 0.0       # δ = 0 
  # # pix_grad_weight: 1.0           # γ(grad) = 1.0


  # grec+gadv
  # pixel_weight: 1.0               # γ
  # feature_weight: 1e-2           # α
  # gan_weight: 1e-3               # β
  # gradient_gan_weight: 1e-3      # δ = 0.001
  # # pix_grad_weight: 1.0           # γ(grad) = 1.0
  #################################################################################

  D_update_ratio: 1
  D_init_iters: 0

  manual_seed: 10
  val_freq: !!float 5e3


#### logger
logger:
  print_freq: 200
  save_checkpoint_freq: !!float 5e3